name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./pocovidscreen/resources/ui
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: |
        cd pocovidscreen/resources/ui
        yarn install
        yarn run build
        cd ../../web_root
        tar cvzf build.tar.gz *
      env:
        CI: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build.tar.gz
        path: ./pocovidscreen/web_root/build.tar.gz
